'use client'

import { useMemo } from 'react'
import {
  buildTruckSessions, summarizeTruckSessions, DAY_SHORT, DEFAULT_TRUCK_DAYS,
  TRUCK_THEORY_TARGET_HOURS, TRUCK_PRACTICAL_TARGET_HOURS,
  formatTime12h, type TruckDay,
} from '@/lib/truck-schedule'

/**
 * Class 1 weekly timetable editor: which days the cohort comes in, and the
 * hours for EACH day (Tue/Thu evenings are theory, Saturday is a full
 * yard + road day — they don't share a time).
 *
 * The preview is generated by the same buildTruckSessions() the API uses, so
 * what's on screen is exactly what gets created.
 *
 * Used by both the new-group wizard and the groups page Setup Class dialog.
 */
export function TruckDaysEditor({
  value,
  onChange,
  sessions,
  startDate,
}: {
  value: TruckDay[]
  onChange: (days: TruckDay[]) => void
  sessions: number
  startDate: string
}) {
  const enabled = useMemo(() => new Map(value.map(d => [d.day, d])), [value])

  const preview = useMemo(
    () => buildTruckSessions(startDate, value, sessions),
    [startDate, value, sessions],
  )
  const summary = useMemo(() => summarizeTruckSessions(preview), [preview])

  const toggleDay = (day: number) => {
    if (enabled.has(day)) {
      onChange(value.filter(d => d.day !== day))
      return
    }
    // Seed a newly enabled day from the program default for that weekday,
    // falling back to an evening theory slot for days the program doesn't use.
    const preset = DEFAULT_TRUCK_DAYS.find(d => d.day === day)
      ?? { day, start: '17:30', end: '21:30', kind: 'theory' as const }
    onChange([...value, preset].sort((a, b) => a.day - b.day))
  }

  const patchDay = (day: number, patch: Partial<TruckDay>) => {
    onChange(value.map(d => (d.day === day ? { ...d, ...patch } : d)))
  }

  const fmtDate = (iso: string) => {
    const [y, m, d] = iso.split('-').map(Number)
    return new Date(y, m - 1, d).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
  }

  return (
    <div className="rounded-md border bg-muted/30 p-3 space-y-3">
      <div>
        <p className="text-xs text-muted-foreground mb-1.5">Class days — each day has its own hours</p>
        <div className="flex gap-1.5 flex-wrap">
          {DAY_SHORT.map((label, day) => {
            const on = enabled.has(day)
            return (
              <button
                key={day}
                type="button"
                onClick={() => toggleDay(day)}
                className={`h-8 w-9 rounded-md text-xs font-medium border transition-colors ${
                  on ? 'bg-primary text-primary-foreground border-primary' : 'bg-background hover:bg-muted'
                }`}
              >
                {label}
              </button>
            )
          })}
        </div>
      </div>

      {value.length > 0 && (
        <div className="space-y-1.5">
          {[...value].sort((a, b) => a.day - b.day).map(d => (
            <div key={d.day} className="flex items-center gap-2 text-xs">
              <span className="w-9 font-medium">{DAY_SHORT[d.day]}</span>
              <input
                type="time"
                value={d.start}
                onChange={e => patchDay(d.day, { start: e.target.value })}
                className="h-8 rounded-md border border-input bg-background px-2"
              />
              <span className="text-muted-foreground">to</span>
              <input
                type="time"
                value={d.end}
                onChange={e => patchDay(d.day, { end: e.target.value })}
                className="h-8 rounded-md border border-input bg-background px-2"
              />
              <select
                value={d.kind}
                onChange={e => patchDay(d.day, { kind: e.target.value as TruckDay['kind'] })}
                className="h-8 rounded-md border border-input bg-background px-2 flex-1 min-w-0"
              >
                <option value="theory">Theory</option>
                <option value="practical">Yard + road</option>
              </select>
            </div>
          ))}
        </div>
      )}

      {preview.length > 0 ? (
        <div className="text-xs space-y-1 border-t pt-2">
          <p>
            <span className="font-medium">{preview.length} classes</span>
            {summary.firstDate && summary.lastDate && (
              <span className="text-muted-foreground"> · {fmtDate(summary.firstDate)} → {fmtDate(summary.lastDate)}</span>
            )}
          </p>
          <p>
            <span className={summary.theoryHours >= TRUCK_THEORY_TARGET_HOURS ? 'text-green-700' : 'text-amber-700'}>
              {summary.theoryHours} h theory
            </span>
            <span className="text-muted-foreground"> of {TRUCK_THEORY_TARGET_HOURS} h</span>
            {' · '}
            <span className={summary.practicalHours >= TRUCK_PRACTICAL_TARGET_HOURS ? 'text-green-700' : 'text-amber-700'}>
              {summary.practicalHours} h yard + road
            </span>
            <span className="text-muted-foreground"> of {TRUCK_PRACTICAL_TARGET_HOURS} h</span>
          </p>
          <p className="text-muted-foreground">
            All in person at the school · a reminder is sent on each class day
            {preview.some(s => {
              const [h, m] = s.start.split(':').map(Number)
              return h * 60 + m < 11 * 60
            }) && ' (2 h before on morning days)'}
          </p>
          <p className="text-muted-foreground">
            First: {fmtDate(preview[0].date)} {formatTime12h(preview[0].start)}
            {preview[0].kind === 'practical' ? ' · yard + road' : ' · theory'}
          </p>
        </div>
      ) : (
        <p className="text-xs text-muted-foreground border-t pt-2">
          Pick a first class date and at least one class day.
        </p>
      )}
    </div>
  )
}
