import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { getStudentById } from '@/lib/external-db'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

import { MEDICAL_CONDITIONS as CONDITIONS } from '@/lib/medical'

function wrap(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let cur = ''
  for (const w of words) {
    if ((cur + ' ' + w).trim().length > maxChars) {
      if (cur) lines.push(cur)
      cur = w
    } else {
      cur = (cur + ' ' + w).trim()
    }
  }
  if (cur) lines.push(cur)
  return lines
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ studentId: string }> },
) {
  const { studentId } = await params
  const id = parseInt(studentId)
  if (isNaN(id)) return NextResponse.json({ error: 'Invalid id' }, { status: 400 })

  const dbStudent = await getStudentById(id)
  if (!dbStudent) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const phone = dbStudent.phone_number?.replace(/\D/g, '') || ''
  const phoneSearch = phone.length > 10 ? phone.slice(-10) : phone

  const reg = await prisma.studentRegistration.findFirst({
    where: {
      OR: [
        { externalId: id },
        ...(phoneSearch.length >= 7 ? [{ phoneNumber: { contains: phoneSearch } }] : []),
      ],
      status: { in: ['confirmed', 'submitted'] },
    },
    orderBy: { createdAt: 'desc' },
  })

  let parsed: { conditions?: number[]; none?: boolean; attestedAt?: string | null } = {}
  if (reg?.medical) {
    try { parsed = JSON.parse(reg.medical) } catch { /* keep empty */ }
  }
  const checked = new Set(parsed.conditions || [])
  const noneChecked = !!parsed.none

  // Build the PDF (US Letter portrait — same proportions as the SAAQ form).
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const ink = rgb(0.06, 0.07, 0.09)
  const muted = rgb(0.4, 0.42, 0.48)
  const blue = rgb(0.12, 0.25, 0.8)

  // Header bar
  page.drawRectangle({ x: 0, y: 762, width: 612, height: 30, color: blue })
  page.drawText('Self-Declaration of Medical Information', {
    x: 36, y: 770, size: 14, font: bold, color: rgb(1, 1, 1),
  })
  page.drawText('SAAQ form 6224A · Generated by Qazi Driving School', {
    x: 36, y: 745, size: 9, font, color: muted,
  })

  // Identity block
  let y = 720
  const drawField = (label: string, value: string, x: number, w: number) => {
    page.drawText(label, { x, y, size: 8, font, color: muted })
    page.drawText(value || '—', { x, y: y - 14, size: 11, font, color: ink })
    page.drawLine({ start: { x, y: y - 18 }, end: { x: x + w, y: y - 18 }, thickness: 0.5, color: muted })
  }
  drawField('LAST NAME', (dbStudent.full_name || '').split(' ').slice(-1).join(' '), 36, 250)
  drawField('FIRST NAME', (dbStudent.full_name || '').split(' ').slice(0, -1).join(' '), 300, 250)
  y -= 40
  drawField('DATE OF BIRTH', dbStudent.dob || reg?.dob || '', 36, 200)
  drawField('PHONE', dbStudent.phone_number || '', 240, 200)
  drawField('PERMIT NO.', dbStudent.permit_number || '', 444, 130)
  y -= 40
  drawField('ADDRESS', dbStudent.full_address || '', 36, 540)
  y -= 40
  drawField('CITY', dbStudent.city || '', 36, 200)
  drawField('PROVINCE', 'QC', 240, 80)
  drawField('POSTAL CODE', dbStudent.postal_code || '', 340, 130)
  y -= 30

  // Disclosure paragraph
  page.drawText(
    'Per the Highway Safety Code, you must inform the SAAQ of any new health problem or deterioration of your',
    { x: 36, y, size: 9, font, color: ink },
  )
  page.drawText(
    'state of health that has not yet been reported. Check any boxes that apply.',
    { x: 36, y: y - 12, size: 9, font, color: ink },
  )
  y -= 32

  // 17 conditions in 2 columns
  const colW = 270
  const rowH = 26
  const startY = y
  for (let i = 0; i < CONDITIONS.length; i++) {
    const col = i % 2
    const row = Math.floor(i / 2)
    const cx = 36 + col * (colW + 10)
    const cy = startY - row * rowH
    const isChecked = checked.has(i + 1)

    // Checkbox
    page.drawRectangle({
      x: cx, y: cy - 9, width: 10, height: 10,
      borderColor: ink, borderWidth: 0.6,
      color: isChecked ? blue : rgb(1, 1, 1),
    })
    if (isChecked) {
      page.drawText('X', { x: cx + 1.5, y: cy - 8, size: 9, font: bold, color: rgb(1, 1, 1) })
    }

    // Number + label (wrapped)
    const num = String(i + 1).padStart(2, '0')
    const lines = wrap(`${num}. ${CONDITIONS[i]}`, 50)
    page.drawText(lines[0] ?? '', { x: cx + 14, y: cy - 1, size: 7.5, font, color: ink })
    if (lines[1]) page.drawText(lines[1], { x: cx + 14, y: cy - 9, size: 7.5, font, color: ink })
    if (lines[2]) page.drawText(lines[2], { x: cx + 14, y: cy - 17, size: 7.5, font, color: ink })
  }
  y = startY - Math.ceil(CONDITIONS.length / 2) * rowH - 16

  // None-of-the-above
  page.drawRectangle({
    x: 36, y: y - 9, width: 10, height: 10,
    borderColor: ink, borderWidth: 0.6,
    color: noneChecked ? rgb(0.18, 0.66, 0.29) : rgb(1, 1, 1),
  })
  if (noneChecked) {
    page.drawText('X', { x: 37.5, y: y - 8, size: 9, font: bold, color: rgb(1, 1, 1) })
  }
  page.drawText(
    'I do not have any of the health problems listed above and I have no new health problem to declare.',
    { x: 50, y: y - 1, size: 9, font: bold, color: ink },
  )
  y -= 32

  // Attestation
  page.drawText('I confirm that I have indicated the situation(s) concerning me.', {
    x: 36, y, size: 10, font, color: ink,
  })
  y -= 32

  // Signature
  if (reg?.signatureImage) {
    try {
      const dataUrl = reg.signatureImage
      const m = /^data:image\/(png|jpeg);base64,(.+)$/.exec(dataUrl)
      if (m) {
        const bytes = Buffer.from(m[2], 'base64')
        const img = m[1] === 'png' ? await doc.embedPng(bytes) : await doc.embedJpg(bytes)
        const w = 200
        const h = (img.height / img.width) * w
        page.drawImage(img, { x: 36, y: y - h, width: w, height: h })
        page.drawLine({ start: { x: 36, y: y - h - 4 }, end: { x: 36 + w, y: y - h - 4 }, thickness: 0.5, color: muted })
        page.drawText('Signature', { x: 36, y: y - h - 18, size: 8, font, color: muted })
      } else {
        page.drawText('[Signature on file]', { x: 36, y, size: 9, font, color: muted })
      }
    } catch {
      page.drawText('[Signature on file]', { x: 36, y, size: 9, font, color: muted })
    }
  } else {
    page.drawLine({ start: { x: 36, y: y - 30 }, end: { x: 250, y: y - 30 }, thickness: 0.5, color: muted })
    page.drawText('Signature', { x: 36, y: y - 44, size: 8, font, color: muted })
  }

  const dateStr = parsed.attestedAt
    ? new Date(parsed.attestedAt).toISOString().split('T')[0]
    : ''
  page.drawLine({ start: { x: 320, y: y - 30 }, end: { x: 520, y: y - 30 }, thickness: 0.5, color: muted })
  page.drawText(dateStr, { x: 320, y: y - 24, size: 11, font, color: ink })
  page.drawText('Date (YYYY-MM-DD)', { x: 320, y: y - 44, size: 8, font, color: muted })

  // Footer
  page.drawText(
    'Original SAAQ form 6224A. Reproduced for student record. Source: saaq.gouv.qc.ca',
    { x: 36, y: 30, size: 7.5, font, color: muted },
  )

  const pdfBytes = await doc.save()

  const safeName = (dbStudent.full_name || `student-${id}`).replace(/[^a-z0-9]+/gi, '_').toLowerCase()
  return new NextResponse(pdfBytes as unknown as BodyInit, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="medical-${safeName}-${id}.pdf"`,
      'Cache-Control': 'no-store',
    },
  })
}
